# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: reactbasics CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      
    - name: setting up node js environment
      uses: actions/setup-node@v2-beta
      with:
        version: 12
        
    - name: Github Actions for yarn
      uses: Borales/actions-yarn@v2.1.0
      with:
        cmd: install
        
    - name: Creating build
      run : yarn build
    
    - name: installing surge
      run:  npm install -g surge
    
    - name: deploying on surge
      run: surge ./build http://bootcamp2020_sayyam.surge.sh/ --token ${{secrets_SURGE_TOKEN}}
